name: Linky Geredis
description: Sync Energy dashboards with your Linky Geredis smart meter
version: 1.5.4
slug: linky-geredis
init: false
url: https://github.com/m-maillot/ha-linky-geredis
image: ghcr.io/m-maillot/ha-linky-geredis-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
map:
  - addon_config
options:
  meters:
    - prm: ''
      token: ''
      name: 'Linky Geredis consumption'
      action: 'sync'
      production: false
    - prm: ''
      token: ''
      name: 'Linky Geredis production'
      action: 'sync'
      production: true
  costs: []
schema:
  meters:
    - prm: str?
      token: str?
      name: str?
      action: list(sync|reset)
      production: bool?
  costs:
    - price: float
      prm: str?
      after: str?
      before: str?
      weekday:
        - str?
      start_date: str?
      end_date: str?
